### ISSUE TITLE
kubectl logs podname 没有日志输出

### ISSUE THREAD

**Issue by skymyyang** [unixhot/salt-kubernetes#8]
使用kubectl logs pod名称   会出现以下报错信息：
error: You must be logged in to the server (the server has asked for the client to provide credentials ( pods/log docker-service-deployment-6b6db5675b-v4lgf))

麻烦赵班长有时间帮忙看一下是何问题，在api的日志中也没有看到相关报错信息，按照网上的说法，创建apiserver-to-kubelet-rbac 后也依然出现该问题。

**Comment by skymyyang** [comment]
班长，我解决了这个bug，是因为权限问题，我们必需创建一个 apiserver-to-kubelet-rbac.yml 来定义权限，以供我们执行 logs、exec 等指令，这是应为从1.8开始kubelet默认关闭了匿名访问。

**Comment by unixhot** [comment]
感谢，已经解决
